config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "feed#index"

  resources :posts do
    member do
      get "delete" => "posts#delete", as: :delete
      post "react" => "reactions#create", as: :react
    end

    resources :comments do
      member do
        get "delete" => "comments#delete", as: :delete
      end
    end
  end

  resources :users, path: "profile", only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :reactions, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  mount_uploader :photo, PhotoUploader

  validates :body, presence: true

  def likes
    count = reactions.select{|r| r.reaction_type.to_sym == :like }.size
    return count if count != 0
  end

  def hearts
    count = reactions.select{|r| r.reaction_type.to_sym == :heart }.size
    return count if count != 0
  end

  def frowns
    count = reactions.select{|r| r.reaction_type.to_sym == :frown }.size
    return count if count != 0
  end

  def comments_count
    count = comments.to_a.size
    return count if count != 0
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :post
  belongs_to :user

  enum reaction_type: [:like, :heart, :frown]

  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts
  has_many :comments
  has_many :reactions

  validates :terms, acceptance: { message: "You must accept the terms and conditions to proceed" }
  validates :first_name, presence: true
  validates :last_name, presence: true

  mount_uploader :avatar, AvatarUploader

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :terms])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, except: [:index, :new, :create]
  before_action :check_ownership, except: [:index, :new, :create, :show]

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_url(@comment.post) }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_url(@comment.post) }
      end
    end
  end

  def delete
    respond_to do |format|
      format.js { render :delete }
    end
  end

  def destroy
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to post_url(@comment.post) }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body).merge(user: current_user, post: @post)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def check_ownership
      return head(403) if @comment.user_id != current_user.id
    end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :redirect_to_feed

  def index
    @post = Post.new
    @posts = Post.includes(:user, :reactions).order(created_at: :desc)

    respond_to do |format|
      format.html 
    end
  end

  def redirect_to_feed
    return redirect_to new_user_session_url if current_user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :new, :create]
  before_action :check_ownership, except: [:index, :new, :create, :show]

  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
    
    respond_to do |format|
      format.js
    end
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      respond_to do |format|
        format.html { redirect_to :root }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url }
      end
    end
  end

  def delete
    respond_to do |format|
      format.js { render :delete }
    end
  end

  def destroy
    if @post.destroy
      redirect_to :root, notice: "Post was successfully deleted."
    end
  end

  private
    def post_params
      params.require(:post).permit(:body, :photo).merge(user: current_user)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def check_ownership
      return head(403) if @post.user_id != current_user.id
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def create
    reaction = Reaction.find_by(
      user_id: current_user.id, 
      post_id: params[:id]
    )

    reaction.destroy if reaction.present?

    if reaction&.reaction_type.to_s != reaction_params[:reaction_type] || reaction.blank?
      Reaction.create!(reaction_params)
    end

    respond_to do |format|
      @post = Post.includes(:reactions).find(params[:id])
      format.js
    end
  end

  private
    def reaction_params
      params.require(:reaction).permit(:reaction_type).merge(user_id: current_user.id, post_id: params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.includes(:posts, :reactions).find_by(id: params[:id])
    @post = Post.new
    @posts = @user.posts.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/comments/delete.js.erb
$('#common-modal').modal('show');
$(".modal-title").text("Are you sure?");
$(".modal-body").html("<%= escape_javascript(render 'comments/partials/delete') %>");

app/views/comments/edit.js.erb
$('#common-modal').modal('show');
$(".modal-title").text("Edit comment");
$(".modal-body").html("<%= escape_javascript(render partial: 'shared/comments/form', locals: {post: @post, comment: @comment}) %>");

app/views/comments/partials/_delete.html.erb
<%= button_to "Yes, delete comment", post_comment_path(@post, @comment), method: :delete, class: "btn btn-danger float-right"%>

app/views/layouts/_feed.html.erb
<%= render 'shared/navbar' %>

<main class="mb-5" style="margin-top: 65px;">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= yield :feed %>
    </div>
  </div>
</main>

<%= render 'shared/modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= yield %>
  </body>
</html>

app/views/posts/delete.js.erb
$('#common-modal').modal('show');
$(".modal-title").text("Are you sure?");
$(".modal-body").html("<%= escape_javascript(render 'posts/partials/delete') %>");

app/views/posts/edit.js.erb
$('#common-modal').modal('show');
$(".modal-title").text("Edit post");
$(".modal-body").html("<%= escape_javascript(render 'shared/posts/form') %>");

app/views/posts/new.js.erb
$('#common-modal').modal('show');
$(".modal-title").text("What's on your mind?");
$(".modal-body").html("<%= escape_javascript(render 'shared/posts/form') %>");

app/views/posts/partials/_delete.html.erb
<%= button_to "Yes, delete post", post_path(@post), method: :delete, class: "btn btn-danger float-right"%>

app/views/posts/partials/_post.html.erb
<div class="post-info">
  <div class="d-flex align-items-streched">
    <%= image_tag post.user.avatar.nav.url, class: "rounded-circle avatar-circle", width: "30", height: "30" %>

    <div>
      <%= link_to user_path(post.user) do %>
        <b><%= post.user.name %></b> 
      <% end %>
      <small><span class="text-secondary"> <%= post.updated_at.strftime("%b %-d, %Y") %></span></small>
      <div><%= post.body %></div>
      <% if post.photo.present? %>
        <div class="mt-2 mb-2">
          <%= image_tag post.photo.url, class: "rounded-card img-fluid" %>
        </div>
      <% end %>

      <div class="mt-2" id="<%= post.id %>-reactions">
        <%= render partial: "shared/reaction_triggers", locals: { post: post } %>
      </div>
    </div>
  </div>
</div>

<% if post.user_id == current_user.id %>
  <div class="dropdown">											
    <button class="btn btn-link dropdown-toggle no-caret" type="button" id="group_option" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-ellipsis-h"></i>
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="group_option">
      <%= link_to "Edit", edit_post_path(post), remote: true, class:"dropdown-item", data: { toggle: "modal", target: "#common-modal"} %>
      <%= link_to "Delete", delete_post_path(post), remote: true, class:"dropdown-item", data: { toggle: "modal", target: "#common-modal"} %>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<% content_for :feed do %>
  <div class="bg-white rounded-card mt-2 p-4 border-0 d-flex justify-content-between align-items-top">
    <%= render partial: "posts/partials/post", locals: { post: @post } %>
  </div>

  <%= render partial: "shared/comments/form", locals: { post: @post, comment: @comment } %>
  <%= render "shared/comments" %>
<% end %>

<%= render 'layouts/feed' %>

app/views/reactions/create.js.erb
$("#<%= @post.id %>-reactions").html("<%= escape_javascript(render partial: 'shared/reaction_triggers', locals: { post: @post }) %>");

app/views/shared/_comments.html.erb
<ul class="list-group list-group-flush bg-light rounded-card">
  <% @comments.each do |comment| %>
    <li class="list-group-item rounded-card d-flex justify-content-between align-items-top mt-2 border-0 ">
      <div class="comment-info">
        <div class="d-flex align-items-streched">
          <%= image_tag comment.user.avatar.nav.url, class: "rounded-circle avatar-circle", width: "30", height: "30" %>
          <div>
            <%= link_to user_path(comment.user) do %>
              <b><%= comment.user.name %></b> 
            <% end %>
            <small><span class="text-secondary"> <%= comment.updated_at.strftime("%b %-d, %Y") %></span></small>
            <div><%= comment.body %></div>
          </div>
        </div>
      </div>

      <% if comment.user_id == current_user.id %>
        <div class="dropdown">											
          <button class="btn btn-link dropdown-toggle no-caret" type="button" id="group_option" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-h"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="group_option">
            <%= link_to "Edit", edit_post_comment_path(comment.post, comment), remote: true, class:"dropdown-item", data: { toggle: "modal", target: "#common-modal"} %>
            <%= link_to "Delete", delete_post_comment_path(comment.post, comment), remote: true, class:"dropdown-item", data: { toggle: "modal", target: "#common-modal"} %>
          </div>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/shared/_modal.html.erb
<div class="modal fade" id="common-modal" tabindex="-1" role="dialog"  aria-labelledby="all-purpose-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">
          <!-- title will be inserted -->
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
      <div class="modal-body">
        <!-- content will be inserted -->
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.erb
<nav class="navbar navbar-light navbar-expand-lg gradient fixed-top bg-light">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "white-logo.png",  width:"80", height:"50", class: "img-fluid" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to root_path, class: "nav-link text-white" do %>
            <i class="fas fa-stream"></i> Feed           
          <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to user_path(current_user), class: "nav-link text-white" do %>
            <i class="fas fa-user"></i> My Post           
          <% end %>
        </li>
      </ul>
    </div>

    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="text-light nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.avatar.nav.url, class: "rounded-circle avatar-circle", width: "30", height: "30" %>   
          <%= current_user.name %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_posts.html.erb
<ul class="list-group list-group-flush bg-light rounded-card">
  <% @posts.each do |post| %>
    <li class="list-group-item rounded-card d-flex justify-content-between align-items-top mt-2 border-0 ">
      <%= render partial: "posts/partials/post", locals: { post: post } %>
    </li>
  <% end %>
</ul>

app/views/shared/_reaction_triggers.html.erb
<div class="d-flex">
  <%= button_to react_post_path(post), params: { reaction: { reaction_type: :like }}, class: "btn btn-sm btn-light m-1", remote: true do %>
    <i class="fas fa-thumbs-up text-secondary"></i> <%= post.likes %>
  <% end %>

  <%= button_to react_post_path(post), params: { reaction: { reaction_type: :heart }}, class: "btn btn-sm btn-light m-1", remote: true do %>
    <i class="fas fa-heart text-secondary"></i> <%= post.hearts %>
  <% end %>

  <%= button_to react_post_path(post), params: { reaction: { reaction_type: :frown }}, class: "btn btn-sm btn-light m-1", remote: true do %>
    <i class="fas fa-frown text-secondary"></i> <%= post.frowns %>
  <% end %>

  <%= link_to post_path(post), class: "btn btn-sm btn-light m-1" do %>
    <i class="fas fa-comments text-secondary"></i> <%= post.comments_count %>
  <% end %>
</div>

app/views/shared/comments/_form.html.erb
<%= form_for [post, comment] do |f| %>
  <div class="bg-white rounded-card mt-2 pt-2 border-0 d-flex align-items-top">
    <div class="col">
      <%= f.text_field :body, {id: "name", class: "form-control mb-2", placeholder: "Add comment" } %>
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-secondary border-0 gradient float-right">Comment</button>
    </div>
  </div>
<% end %>

app/views/shared/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-row">
    <div class="col">
      <div class="<%= 'has-error' if @post.errors.include?(:body) %>">
        <% if @post.errors.include?(:body) %>
          <span class="error"> <%= @post.errors[:body].first %></span>
        <% end %>
        <%= f.text_area :body, {id: "name", class: "form-control" } %>
      </div>
    </div>
    <%= f.file_field :photo, id: "photo-upload", accept: ".png, .jpg, .jpeg", hidden: true %>
  </div>

  <div class="mt-3">
    <label class="btn btn-light" for="photo-upload">
      <i class="fas fa-camera"></i>
    </label>

    <button type="submit" class="btn btn-secondary border-0 gradient float-right">Post</button>
  </div>
<% end %>

app/views/users/show.html.erb
<% content_for :feed do %>
  <div class="bg-primary text-white rounded-card p-2 mt-2">
    <div class="d-block">
      <div class="d-flex align-items-top">
        <%= image_tag @user.avatar.profile.url, class: "rounded-circle avatar-circle", width: "50", height: "50" %>
        <div>
          <div class="font-weight-bolder"><%=  @user.name %></div>
          <small class="d-block">Joined:<%= @user.created_at.strftime("%b %d, %Y") %></small>
          <small class="d-block">Post Count: <%= @user.posts.to_a.size %></small>
        </div>
      </div>
    </div>
  </div>

  <%= render "shared/posts" %>
<% end %>

<%= render 'layouts/feed' %>